export default function AISummaryCard({ summary }) {
  return (
    <div className="bg-white rounded-2xl shadow-md hover:shadow-xl transition-all duration-300 p-6 border border-blue-100">

      {/* Header */}
      <div className="flex items-center gap-3 mb-4">
        <div className="bg-blue-100 text-blue-600 p-2 rounded-full text-xl">
          🤖
        </div>
        <div>
          <h2 className="text-lg font-semibold text-blue-700">
            AI Patient Summary
          </h2>
          <p className="text-xs text-gray-400">
            Generated by Medical AI Engine
          </p>
        </div>
      </div>

      {/* Summary Content */}
      <div className="bg-blue-50 p-4 rounded-lg text-gray-700 leading-relaxed text-sm border border-blue-100">
        {summary ? summary : "No AI summary available yet."}
      </div>

    </div>
  );
}
